---
- name: "Check {{ item }}"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0755"
  check_mode: true
  register: _gitea_dir_check

- name: "Create {{ item }}"
  when: _gitea_dir_check.changed
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0755"
